services:
  fastapi-app:
    # Flexible tag instead of image path
    image: registry.gitlab.com/naturalis/bii/bge/barcode-data-portal/fastapi-app:${IMAGE_VERSION:-latest}
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
    restart: unless-stopped
    # Dynamic number of workers, as this seems to be the only different betweens staging and production environments
    command: gunicorn main:app --workers ${FASTAPI_NR_WORKERS:-4} --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    # As APP_PORT is specified in .env, why not use that instead of hard-coding it
    ports:
      - "8000:${APP_PORT:-8000}"
    # Using Traefik to add the Route53 certificate
    labels:
      - traefik.enable=true
      - traefik.http.routers.uvicorn.entrypoints=websecure
      - traefik.http.routers.uvicorn.tls=true
      - traefik.http.routers.uvicorn.tls.certresolver=route53
      - traefik.http.routers.uvicorn.rule=Host(`${FQDN:-boldsystems.eu}`)
    networks:
      - web
      - backend
    env_file:
      - .env
    depends_on:
      socketserver-logging:
        condition: service_started
      redis:
        condition: service_started
      couchbase:
        condition: service_healthy

  # Leave this for now, but better to just log to stdout/-err in the future?
  socketserver-logging:
    image: registry.gitlab.com/naturalis/bii/bge/barcode-data-portal/socketserver-logging:${IMAGE_VERSION:-latest}
#    build:
#      context: .
#      dockerfile: docker/Dockerfile.socketserver_logging
    restart: unless-stopped
    ports:
      - "9020:9020"
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ${DATA_PATH:-/data}/log/bold-public-portal:/var/log/bold-public-portal

  # Use Traefik instead of nginx as reverse proxy, as it's much easier to setup Let's Encrypt certificates
  traefik:
    image: registry.gitlab.com/naturalis/lib/docker/traefik:v3.2
    restart: unless-stopped
    depends_on:
      - fastapi-app
      - redis
      - docker-socket-proxy
    networks:
      - web
      - backend
      - docker-socket-proxy
    ports:
      - ${HOST_IP:-0.0.0.0}:80:8000
      - ${HOST_IP:-0.0.0.0}:443:443
      # Uncomment to enable dashboard
#      - 127.0.0.1:${TRAEFIK_API_PORT:-8079}:8080
    volumes:
      - ${DATA_PATH:-/data}/letsencrypt:/letsencrypt:rw
    command:
      - --providers.docker=true
      - --global.sendAnonymousUsage=false
      - --providers.docker.exposedByDefault=false
      - --providers.docker.endpoint=tcp://docker-socket-proxy:2375
      - --providers.docker.network=docker-socket-proxy
      - --log.level=ERROR
      - --entrypoints.web.address=:8000
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.route53.acme.dnschallenge=true
      - --certificatesresolvers.route53.acme.dnschallenge.provider=route53
      - --certificatesresolvers.route53.acme.storage=/letsencrypt/route53.json
      - --certificatesresolvers.route53.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      # Uncomment to enable dashboard
#      - --api=true
#      - --api.insecure=true
#      - --log.level=INFO
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-EMPTY_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-EMPTY_AWS_SECRET_ACCESS_KEY}

  redis:
    image: redis:7.0-bookworm
    restart: unless-stopped
    ports:
      - "6379:${REDIS_PORT:-6379}"
    networks:
      - backend

  couchbase:
    image: couchbase:enterprise
    restart: unless-stopped
    ports:
#      - "8091-8097:8091-8097" # Do not expose the non-encrypted web UI ports
      - "18091-18097:18091-18097"
      - "11207:11207"
      - "11210:11210"
      - "11280:11280"
    healthcheck:
      test: curl --silent http://127.0.0.1:8091/pools > /dev/null
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
    env_file:
      - .env
    networks:
      - web
      - backend
    volumes:
      - ${DATA_PATH:-/data}/sample_data:/db_data
      - ${DATA_PATH:-/data}/couchbase:/opt/couchbase/var
    # This probably needs to be adjusted as well, as we don't want to accidentally drop the cluster!
    entrypoint: /db_data/init.sh ${COUCHBASE_DROP_CLUSTER_ON_START:-true}

  docker-socket-proxy:
    image: registry.gitlab.com/naturalis/lib/docker/docker-socket-proxy
    restart: unless-stopped
    networks:
      - docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,delegated
    environment:
      CONTAINERS: 1

networks:
  web:
    internal: false
  backend:
    internal: true
  docker-socket-proxy:
    internal: true
