# This override provides basic authentication to shield off the site with a login

services:
  fastapi-app:
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.uvicorn-auth.basicauth.realm="EU Bold"
      - traefik.http.middlewares.uvicorn-auth.basicauth.users=${BASIC_AUTH:?Add BASIC_AUTH to env file to enable basic authentication}
      - traefik.http.routers.uvicorn.tls=true
      - traefik.http.routers.uvicorn.middlewares=uvicorn-auth
      - traefik.http.routers.uvicorn.rule=Host(`${FQDN:-boldsystems.eu}`)
      - traefik.http.routers.uvicorn.entrypoints=websecure
      - traefik.http.routers.uvicorn.tls.certresolver=route53
