#
# This file is used to build the Docker image of the application
#
# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Update system packages to patch security vulnerabilities (OpenSSL CVEs)
# hadolint ignore=DL3008
RUN set -eux; \
    apt-get update; \
    apt-get upgrade -y; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*;

# Create required directories
RUN mkdir -p /var/log/bold-public-portal

# Set the working directory in the container
WORKDIR /app

# Install any needed dependencies specified in requirements.txt
COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code into the container
COPY src /app

# Expose the application port
EXPOSE 9020

# Run python service when the container launches
CMD ["python", "socketserver_logging.py"]
